image: node:18.16.1-slim
definitions:
  services:
    docker:
      memory: 4096
  steps:
    - step: &build_and_push_docker_image
        size: 2x
        services:
           - docker 
        name: Build and Push Docker Image
        script:
          - apt update
          - apt install curl -y
          - apt install zip -y
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - ./aws/install
          - IMAGE="365330253536.dkr.ecr.eu-west-2.amazonaws.com/pharmlytics-frontend"
          - NAME="pharmlytics-frontend"
          - ENV="${BITBUCKET_BRANCH}";
          - TAG1="${ENV}-${BITBUCKET_BUILD_NUMBER}"
          - TAG2="${ENV}-latest"
          - aws configure set aws_access_key_id "${AWS_KEY}"
          - aws configure set aws_secret_access_key "${AWS_SECRET}"
          - aws ecr get-login-password --region "${AWS_REGION}" | docker login -u AWS --password-stdin $IMAGE
          - aws s3 cp s3://pharmalytics-bi-platform/frontend/${ENV}.env ./.env
          - ls -al
          - docker build -t $NAME:$TAG1 .
          - docker tag $NAME:$TAG1 $IMAGE:$TAG1
          - docker tag $IMAGE:$TAG1 $IMAGE:$TAG2
          - docker push $IMAGE:$TAG1
          - docker push $IMAGE:$TAG2

    - step: &deploy_to_ecs
        size: 2x
        name: Deploy to ECS
        script:
          - ENV="${BITBUCKET_BRANCH}"
          - if [[ "${ENV}" == "master" ]]; then CLUSTER_NAME="${PROD_ECS_CLUSTER_NAME}"; elif [[ "${ENV}" == "qa" ]]; then CLUSTER_NAME="${QA_ECS_CLUSTER_NAME}"; elif [[ "${ENV}" == "develop" ]]; then CLUSTER_NAME="${DEV_ECS_CLUSTER_NAME}"; fi
          - pipe: atlassian/aws-ecs-deploy:1.11.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_KEY
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET
              AWS_DEFAULT_REGION: $AWS_REGION
              CLUSTER_NAME: $CLUSTER_NAME
              SERVICE_NAME: $SERVICE_NAME
              FORCE_NEW_DEPLOYMENT: 'true'
    
    - step: &check_ecs_task_status
        name: Check Deployment Status
        image: xueshanf/awscli:3.10-alpine
        script:
          - ENV="${BITBUCKET_BRANCH}"
          - if [[ "${ENV}" == "master" ]]; then CLUSTER_NAME="${PROD_ECS_CLUSTER_NAME}"; elif [[ "${ENV}" == "qa" ]]; then CLUSTER_NAME="${QA_ECS_CLUSTER_NAME}"; elif [[ "${ENV}" == "develop" ]]; then CLUSTER_NAME="${DEV_ECS_CLUSTER_NAME}"; fi
          - aws configure set aws_access_key_id "${AWS_KEY}"
          - aws configure set aws_secret_access_key "${AWS_SECRET}"
          - export cluster_name=$CLUSTER_NAME
          - export service_name=$SERVICE_NAME
          - export region_name=$AWS_REGION
          - chmod +x check_ecs_task_status.sh
          - ./check_ecs_task_status.sh

pipelines:
  branches:
    '{develop,qa}':
     - step: *build_and_push_docker_image
     - step: *deploy_to_ecs
     - step: *check_ecs_task_status
    '{master}':
     - step:  
         <<: *build_and_push_docker_image
         script: 
          - apt update
          - apt install curl -y
          - apt install zip -y
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - ./aws/install
          - IMAGE="637423645633.dkr.ecr.eu-west-2.amazonaws.com/pharmlytics-frontend"
          - NAME="pharmlytics-frontend"
          - if [[ "${BITBUCKET_BRANCH}" == "master" ]]; then ENV="prod" else ENV="${BITBUCKET_BRANCH}" fi
          - TAG1="${ENV}-${BITBUCKET_BUILD_NUMBER}"
          - TAG2="${ENV}-latest"
          - aws configure set aws_access_key_id "${AWS_KEY_PHARMLYTICS_ACCOUNT}"
          - aws configure set aws_secret_access_key "${AWS_SECRET_PHARMLYTICS_ACCOUNT}"
          - aws ecr get-login-password --region "${AWS_REGION}" | docker login -u AWS --password-stdin $IMAGE
          - aws s3 cp s3://prod-pharmlytics/environment-files/frontend/prod.env ./.env
          - ls -al
          - docker build -f Dockerfile-Prod -t $NAME:$TAG1 .
          - docker tag $NAME:$TAG1 $IMAGE:$TAG1
          - docker tag $IMAGE:$TAG1 $IMAGE:$TAG2
          - docker push $IMAGE:$TAG1
          - docker push $IMAGE:$TAG2
     - step:
         <<: *deploy_to_ecs
         script:
          - ENV="${BITBUCKET_BRANCH}"
          - if [[ "${ENV}" == "master" ]]; then CLUSTER_NAME="${PROD_ECS_CLUSTER_NAME_PHARMLYTICS_ACCOUNT}"; elif [[ "${ENV}" == "qa" ]]; then CLUSTER_NAME="${QA_ECS_CLUSTER_NAME}"; elif [[ "${ENV}" == "develop" ]]; then CLUSTER_NAME="${DEV_ECS_CLUSTER_NAME}"; fi
          - pipe: atlassian/aws-ecs-deploy:1.11.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_KEY_PHARMLYTICS_ACCOUNT
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_PHARMLYTICS_ACCOUNT
              AWS_DEFAULT_REGION: $AWS_REGION
              CLUSTER_NAME: $CLUSTER_NAME
              SERVICE_NAME: $SERVICE_NAME_PHARMLYTICS_ACCOUNT
              FORCE_NEW_DEPLOYMENT: 'true'

