# Stage 1: Build
FROM node:18.16.1-slim AS builder

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install npm dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Serve
FROM node:18.16.1-slim

# Set working directory inside the container
WORKDIR /app

# Copy the built application from the builder stage to the working directory
COPY --from=builder /app/build ./build

# Install serve globally to serve the built application
RUN npm install -g serve

# Specify the command to run when the container starts
CMD ["serve", "-s", "build"]
